config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/', to: 'top_page#index'
  get '/search', to: 'search#search'
  get '/toilet/:id', to: 'toilets#description' , as: 'toilet'

  post '/reviews', to: 'reviews#post', as: 'reviews'

  post '/edit', to: "toilets#edit", as: 'edit'

  resource :bookmarks

  post '/line/callback', to: 'line#callback'

  devise_for :users, controllers: { :omniauth_callbacks => "omniauth_callbacks" }
end

app/models/toilet.rb
class Toilet < ApplicationRecord
    has_many :reviews
    mount_uploader :image_path, ImageUploader

    def findToiletsByGoogleId(toiletId)
        Toilet.find_by(google_id: toiletId)
    end

    def findToiletById(id)
        Toilet.find_by(id: id)
    end

    def self.getToiletInfoByToiletId(placeId)
        key = ENV["GOOGLE_KEY"]
        # hash形式でパラメタ文字列を指定し、URL形式にエンコード
        params = URI.encode_www_form({placeid: placeId,key: key})
        # URIを解析し、hostやportをバラバラに取得できるようにする
        uri = URI.parse("https://maps.googleapis.com/maps/api/place/details/json?#{params}")
        # リクエストパラメタを、インスタンス変数に格納
        
        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = true
        http.verify_mode = OpenSSL::SSL::VERIFY_NONE 
        response = http.start do |h|
          h.open_timeout = 5
          h.read_timeout = 10
          h.get(uri.request_uri)
        end
       
        begin
          case response
          when Net::HTTPSuccess # 結果の受け取り
            resp = JSON.load(response.body)
            result = resp["result"]
        
          when Net::HTTPRedirection
            nil
          else
            nil
          end
        rescue => e
          nil
        
        end
    end
    def self.getPlaceByKeyWord(keyword)
        # hash形式でパラメタ文字列を指定し、URL形式にエンコード
        params = URI.encode_www_form({q: keyword})
        # URIを解析し、hostやportをバラバラに取得できるようにする
        uri = URI.parse("https://www.geocoding.jp/api/?#{params}")
        # リクエストパラメタを、インスタンス変数に格納
        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = true
        http.verify_mode = OpenSSL::SSL::VERIFY_NONE 
        response = http.start do |h|
          h.open_timeout = 5
          h.read_timeout = 10
          h.get(uri.request_uri)
        end
    
        begin
          case response
          when Net::HTTPSuccess # 結果の受け取り
            resp = XmlSimple.xml_in(response.body.to_str)
          when Net::HTTPRedirection
            nil
          else
            
            nil
          end
        rescue => e
          nil
        end
    end

    def self.getToiletList(lat,lng)
        
        key = ENV["GOOGLE_KEY"]
        location = "#{lat},#{lng}"
        
        # hash形式でパラメタ文字列を指定し、URL形式にエンコード
        params = URI.encode_www_form({key: key, location: location, radius: 2000, keyword: "トイレ"})
        # URIを解析し、hostやportをバラバラに取得できるようにする
        uri = URI.parse("https://maps.googleapis.com/maps/api/place/nearbysearch/json?#{params}")
        # リクエストパラメタを、インスタンス変数に格納
        
        http = Net::HTTP.new(uri.host, uri.port)
        http.use_ssl = true
        http.verify_mode = OpenSSL::SSL::VERIFY_NONE 
        response = http.start do |h|
          h.open_timeout = 5
          h.read_timeout = 10
          h.get(uri.request_uri)
        end
    
        begin
          case response
          when Net::HTTPSuccess # 結果の受け取り
            resp = JSON.load(response.body)
            result = []

            resp["results"].each_with_index do |value, index| 
                p = value
                r = Toilet.find_by(google_id: value["place_id"])
                if r != nil then 
                    p["name"] = r.name
                    p["description"] = r.description
                    p["valuation"] = r.valuation
                    p["icon"] = r.image_path #"https://maps.gstatic.com/mapfiles/place_api/icons/generic_business-71.png"
                else
                    p["description"] = ""
                    p["valuation"] = 0.0
                    p["icon"] = "/default.jpg"
                end
                result.push(p)
            end
           
            return result
          when Net::HTTPRedirection
            nil
          else
            nil
          end
        rescue => e
          logger.debug(e)
        end
    end

    def getPopularToilets
        Toilet.select(Arel.star).order(:valuation).reverse_order.limit(20)
    end

end

app/controllers/toilets_controller.rb
class ToiletsController < ApplicationController
    def description
        placeId = params[:id]
        
        @toiletId = placeId
        toilet = Toilet.find_by(google_id: placeId)
        @reviews = []
        unless toilet.nil? then
            res = Review.select(Arel.star).where(Review.arel_table[:toilet_id].eq(toilet.id)).joins(
                Review.arel_table.join(User.arel_table).on(
                  User.arel_table[:id].eq(Review.arel_table[:user_id])
                ).join_sources
              )
            @reviews = res.as_json
        end    
        
        resp = JSON.load(response.body)
        @result = Toilet.getToiletInfoByToiletId(placeId)
        
        r = Toilet.new.findToiletsByGoogleId(placeId)
        unless r.nil? then 
            value = Review.new.calcValuationByToiletId(r.id)
            @result["name"] = r.name
            @result["icon"] = r.image_path
            @result["description"] = r.description
            @result["valuation"] = value
            r.valuation = value
            @valueImg = Review.new.getStarPathByValuation(value)
            r.save
        else
            @result["description"] = ""
            @result["valuation"] = 0.0
            @result["icon"] = "/default.jpg"
            @valueImg = "1_star.png"
        end
        
        @list = Toilet.getToiletList(@result["geometry"]["location"]["lat"],@result["geometry"]["location"]["lng"])
        
        render 'toilets/toilets'
          
    end



    def edit
        tId = params[:toiletId]
        toilet = Toilet.new.findToiletsByGoogleId(tId)
        if toilet.nil? then 
            toiletByAPI = Toilet.getToiletInfoByToiletId(tId)
            t = Toilet.create(
                name: toiletByAPI["name"],
                google_id: tId,
                lat: toiletByAPI["geometry"]["location"]["lat"],
                lng: toiletByAPI["geometry"]["location"]["lng"],
                geolocation: toiletByAPI["formatted_address"],
                description: "",
            )
            t.image_path = Rails.root.join("public/default.jpg").open
            t.save()
            toilet = Toilet.new.findToiletsByGoogleId(tId)
        end
        unless params[:image_path].blank? then  
            toilet.image_path = params[:image_path]
        end
        if params[:toiletName] != "" then
            toilet.name = params[:toiletName]
        end
        if params[:toiletDescription] != "" then
            toilet.description = params[:toiletDescription]
        end
        toilet.save
        redirect_to "/toilet/#{tId}"
    end
end

app/helpers/toilets_helper.rb
module ToiletsHelper
end

app/views/toilets/toilets.html.erb
<html>
    <head>
        <meta charset=“UFT-8”>
        <title>CSS</title>
        <%= stylesheet_link_tag 'top', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= stylesheet_link_tag 'header', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= stylesheet_link_tag 'body', media: 'all', 'data-turbolinks-track': 'reload' %>
        <!--
        <link rel="stylesheet" type="text/css" href="header.css">
        <link rel="stylesheet" type="text/css" href="body.css">
        <link rel="stylesheet" type="text/css" href="top.css">
        -->
        <style>
            #map {
              height: 400px;
              width: 100%;
             }
    </style>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    </head>
    <body>
        
        <%= render partial: "components/header" %>

        <div class="toiletDescriptionTextContainer">
                <div class="toiletDescriptionText">
                        <h2 class="toiletDescriptionName">
                            <%= @result["name"] %>
                        </h2>
                        <div class="descriptionValueContainer">
                            <%= image_tag @valueImg ,class: "descriptionValueImage"%>
                            <h2 class="toiletValuation">
                                <%= @result["valuation"] %>
                            </h2>
                        </div>
                        
                        <p class="toiletDescriptionAddress">
                            <%= @result["formatted_address"] %>
                        </p>
                </div>     
        </div>
        <div class="toiletBodyContainer">
                
                <div class="toiletDescriptionContainer">
                    <div class="toiletInfo">
                        <%= image_tag @result["icon"], class: 'toiletDescriptionImage' %>
                        <p class="toiletDescriptionDescription">
                                <%= @result["description"]%>
                        </p>
                    </div>
                    <div id="map"></div>

                    <%= javascript_tag() do -%>
                      function initMap() {
                        var uluru = {lat: <%= @result["geometry"]["location"]["lat"]%>, lng: <%= @result["geometry"]["location"]["lng"]%>};
                        var map = new google.maps.Map(document.getElementById('map'), {
                          zoom: 18,
                          center: uluru
                        });
                        var marker = new google.maps.Marker({
                          position: uluru,
                          map: map
                        });
                      }
                    <% end -%>

                    <script async defer
                        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD6pvQJvfU75uOpTGUsdKlWk5tPIfFrIH8&callback=initMap">
                    </script>

                    <% if user_signed_in? %>
                        <div class="buttonContainer">
                            <%= form_tag(bookmarks_path, method: :post, id: "bookmarkButton") do -%>
                                <%= hidden_field_tag :toiletId , @toiletId %>
                                <%= submit_tag "お気に入り登録", data: { disable_with: "送信済" }, id: :bookmarkSubmitButton %>
                            <% end -%>

                            <input type="button" value="編集する" id="showTextAreaButton">
                        </div> 
                        <%= form_tag(edit_path, method: :post,id: "editArea",style: "display: none;",:multipart => true) do -%>
                            <p class="toilet">トイレの名前</p>
                            <%= text_field_tag(:toiletName, "",class: :nameField) %>
                            <p class="toilet">トイレの説明</p>
                            <%= text_area_tag(:toiletDescription, "",class: :descriptionField) %>
                            <%= file_field_tag(:image_path) %>
                          <%= hidden_field_tag :toiletId , @toiletId %>
                          <%= submit_tag "投稿", data: { disable_with: "送信済" },id: :submitDescriptionButton %>
                        <% end -%>
                        
                    <% end %>
                    <% if user_signed_in? %>
                    <div class="postReviewContainer">
                        <p class="postReviewTitle">レビュー</p>
                            <%= form_tag(reviews_path, method: :post) do -%>
                              <%= select_tag :valuation, options_for_select(["1", "2", "3", "4", "5"]), id: :valuationInput %>
                              <%= text_area_tag(:message,"",id: :reviewMessage) %>
                              <%= hidden_field_tag :toiletId , @toiletId %>
                              <%= submit_tag "投稿", data: { disable_with: "送信済" }, id: :submitReviewButton %>
                            <% end -%>
                        </div>
                    <% end %>

                    <div class="toiletReviewsContainer">
                        <ul class="toiletDescriptionReviewsList">
                            <% @reviews.each do |r| %>
                                <li class="toiletDescriptionReviewContent">
                                    <%= image_tag r["image_url"], id: :userIcon%>
                                    <div class="userReviewTextContainer">
                                            <p class="reviewerName"> 
                                                <%= r["username"] %>
                                            </p>
                                            <p class="valuation">
                                                <%= r["valuation"] %>
                                            </p>
                                            <p class="reviewText">
                                                <%= r["message"]%>
                                            </p>
                                    </div>
                                </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
                <div class="nearToiletsContainer">
                    <h3>周辺のトイレ</h3>
                    <ul>
                        <% @list.each do |r| %>
                        <li class="nearToiletContent">
                            <%= image_tag r["icon"], class: 'nearToiletContentImage' %>
                            <div class="toiletText">
                                <p class="toiletName">
                                    <%= link_to(r["name"], toilet_path(r["place_id"]))%>
                                </p>
                            </div>
                        </li>
                        <% end %>
                    </ul>
                </div>
            
        </div>
        <%= javascript_tag() do -%>
            $(document).ready(function(){
                $('#showTextAreaButton').click(function(){
                    $('#editArea').show();
                });
            });
        <% end -%>
    </body>
</html>